### PR TITLE
add the meta for the robots

### PR DESCRIPTION
**Pull request by nicolasThal**
[OO-MISC] Add the robots meta in the page header

### CODE REVIEW

**Comment by ngilain** [comment]
@nicolasThal : It seems the mechanism of default fallback is not coded : only the settings in the node are taken in account.

**Comment by nicolasThal** [comment]
The fallback is done at the node creation, in the `BackofficeBundle\NodeManager` we copy the value from the site

**Comment by ngilain** [comment]
you're right, my bad :)
:+1:

**Comment by mraiffe** [comment]
:+1:

**Pull request merged**
